kind: pipeline
name: ruby-2-6
group: build

steps:
- name: install
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: integration
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test integration

- name: quality
  image: ruby:2.6
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - CI=true bundle exec rake codecov:upload

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: ruby-2-5
group: build

steps:
- name: install
  image: ruby:2.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: integration
  image: ruby:2.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test integration

- name: quality
  image: ruby:2.5
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - CI=true bundle exec rake codecov:upload

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: ruby-2-4
group: build

steps:
- name: install
  image: ruby:2.4
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.4
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.4
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: integration
  image: ruby:2.4
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test integration

- name: quality
  image: ruby:2.4
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - CI=true bundle exec rake codecov:upload

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: ruby-2-3
group: build

steps:
- name: install
  image: ruby:2.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: integration
  image: ruby:2.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test integration

- name: quality
  image: ruby:2.3
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - CI=true bundle exec rake codecov:upload

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: jruby-9-2
group: build

steps:
- name: install
  image: hanami/jruby-9.2
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: hanami/jruby-9.2
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: integration
  image: hanami/jruby-9.2
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test integration

- name: quality
  image: hanami/jruby-9.2
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - CI=true bundle exec rake codecov:upload

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: jruby-9-1
group: build

steps:
- name: install
  image: hanami/jruby-9.1
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: hanami/jruby-9.1
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: integration
  image: hanami/jruby-9.1
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test integration

- name: quality
  image: hanami/jruby-9.1
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - CI=true bundle exec rake codecov:upload

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: slack
group: build

clone:
  disable: true

depends_on:
  - jruby-9-1

steps:
- name: slack
  image: plugins/slack
  settings:
    link_names: true
    webhook:
      from_secret: slack
      channel: dev
  when:
    event:
    - push
